In [48]:
pip install word2number

  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5583 sha256=4a1b868668bdeb4aea20f3de03f79e3302d518790eef57fc0f04d752d1954fd9
  Stored in directory: c:\users\asus\appdata\local\pip\cache\wheels\a0\4a\5b\d2f2df5c344ddbecb8bea759872c207ea91d93f57fb54e816e
Successfully built word2number
Note: you may need to restart the kernel to use updated packages.


In [49]:
import numpy as np
import pandas as pd
from sklearn import linear_model 
from word2number import w2n

In [9]:
df = pd.read_csv('homeprices1.csv')
df
#in this data there is an empty value.

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
df_median = df.bedrooms.median()

In [5]:
df_median

4.0

In [14]:
#preprocess the data(filling the NaN data)
df.bedrooms = df.bedrooms.fillna(df_median)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [22]:
#training data set with exitsting values
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms','age']],df.price)

LinearRegression()

In [16]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [18]:
reg.intercept_

221323.00186540384

In [19]:
reg.predict([[3000,4,40]])

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([521797.13165825])

## Exercise

In [55]:
dd = pd.read_csv('hiring.csv')
dd

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [56]:
dd.experience = dd.experience.fillna("zero")
dd

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [57]:
dd.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [58]:
dd.experience = dd.experience.apply(w2n.word_to_num)
dd

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [67]:
test_median = dd['test_score(out of 10)'].median()
test_median
# dd['test_score(out of 10)'] = dd['test_score(out of 10)'].fillna(test_median)
# dd

8.0

In [61]:
#train the data set
reg2 = linear_model.LinearRegression()
reg2.fit(dd[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], dd['salary($)'])

LinearRegression()

In [62]:
reg2.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [63]:
reg2.intercept_

17737.263464337688

In [64]:
reg2.predict([[2, 9, 6]])

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [65]:
reg2.predict([[12, 10, 10]])

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])